# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
# \
$username\
$hostname\
$directory\
$git_branch\
$git_status\
(\
$bun\
$c\
$cmake\
$dart\
$dotnet\
$golang\
$gradle\
$java\
$kotlin\
$lua\
$nodejs\
$package\
$php\
$python\
$rlang\
$ruby\
$rust\
$scala\
)\
$container\
$fill\
\\[\
$time\
\\]\
$battery\
$cmd_duration\
$linebreak
$character\
"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[cmd_duration]
disabled = false
format = '\([$duration]($style)\)'
min_time = 5000

[username]
disabled = false
show_always = true
format = '[$user]($style)'
style_user = "bright-green bold"
style_root = "red bold"
aliases = {} #{ "soda" = "hilbert" }

[hostname]
format = '@[$hostname$ssh_symbol]($style) '
style = "purple"
ssh_only = false

[directory]
format = 'in [$path]($style)[($read_only)]($read_only_style) '
read_only = '!'
truncate_to_repo = false

[git_branch]
format = 'on [git:$branch(:$remote_branch)]($style)'

[git_status]
format = '[$all_status$ahead_behind]($style) '
ahead = 'x${count}'
diverged = 'x${ahead_count}⇣${behind_count}'
behind = 'x${count}'
windows_starship = '/mnt/c/Users/username/scoop/apps/starship/current/starship.exe'

[fill]
symbol = ' '

[os]
disabled = true
format = '[$symbol]($style)'
style = "bright-white bold"

[battery]
format = '\[[$percentage]($style)\]'

[[battery.display]]
threshold = 20
style = 'bold red'

[[battery.display]]
threshold = 50
style = 'bold orange'

[[battery.display]]
threshold = 90
style = 'bold green'

[time]
disabled = false
format = '[$time]($style)'
