"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[input]
prepend_keymap = [
	{ on = [ "<Esc>" ], run = "close", desc = "Cancel input" },
	{ on = [ "l" ], run = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file" },
]
